language: shell

addons: 
  apt_packages:
    - graphviz

script: ./generate.sh

deploy:
  provider: pages
  target_branch: graphics
  local_dir: build
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  on:
    branch: main
